CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=0
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=0
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=20
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=20
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=40
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=40
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=60
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=60
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=80
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=80
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=100
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=100
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=200
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=200
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=300
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=300
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=400
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=400
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=500
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=500
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=600
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=600
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=700
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=700
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=800
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=800
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=900
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=900
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=999
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_seed5 --split val --save_iter=999


CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=0
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=0
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=20
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=20
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=40
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=40
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=60
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=60
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=80
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=80
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=100
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=100
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=200
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=200
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=300
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=300
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=400
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=400
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=500
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=500
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=600
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=600
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=700
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=700
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=800
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=800
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=900
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=900
CUDA_VISIBLE_DEVICES=1 python save_features.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=999
CUDA_VISIBLE_DEVICES=1 python test.py --model ResNet18 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/ResNet18_baseline_aug_seed5 --split val --save_iter=999

CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=0
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=0
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=20
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=20
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=40
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=40
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=60
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=60
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=80
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=80
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=100
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=100
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=200
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=200
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=300
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=300
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=400
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=400
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=500
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=500
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=600
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=600
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=700
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=700
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=800
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=800
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=900
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=900
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=999
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_seed5 --split val --save_iter=999


CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=0
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=0
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=20
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=20
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=40
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=40
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=60
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=60
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=80
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=80
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=100
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=100
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=200
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=200
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=300
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=300
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=400
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=400
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=500
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=500
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=600
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=600
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=700
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=700
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=800
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=800
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=900
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=900
CUDA_VISIBLE_DEVICES=1 python save_features.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=999
CUDA_VISIBLE_DEVICES=1 python test.py --model Conv6 --method baseline --dataset CUB --ckpt_dir /root/autodl-tmp/checkpoints/CUB/Conv6_baseline_aug_seed5 --split val --save_iter=999

